apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-hello-docker-tested
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-hello-docker-tested
    app.kubernetes.io/part-of: java-quarkus-hello-docker-tested
  name: java-quarkus-hello-docker-tested
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-hello-docker-tested
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-hello-docker-tested
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bsutter-tenant/java-quarkus-hello-docker-tested/java-quarkus-hello-docker-tested@sha256:6c0142376dc02d0e59110b34cccf2c5146ae8d429d8070aacf692db2eab805e9
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
